[book]
authors = ["diegobianqui"]
language = "en"
multilingual = false
src = "src"
title = "Bitcoin Core Development Study Guide"

[output.html]
git-repository-url = "https://github.com/diegobianqui/BOSS_Syllabus"
edit-url-template = "https://github.com/diegobianqui/BOSS_Syllabus/edit/main/src/{path}"
